FROM ubuntu:22.04
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y lsb-release net-tools curl tcpdump iputils-ping sudo gnupg2 vim netbase openssh-server netcat
# add GPG key
RUN curl -s https://deb.frrouting.org/frr/keys.gpg | sudo tee /usr/share/keyrings/frrouting.gpg > /dev/null
# possible values for FRRVER: frr-6 frr-7 frr-8 frr-9 frr-stable
# frr-stable will be the latest official stable release
ENV FRRVER="frr-stable"
RUN echo deb '[signed-by=/usr/share/keyrings/frrouting.gpg]' https://deb.frrouting.org/frr $(lsb_release -s -c) $FRRVER | sudo tee -a /etc/apt/sources.list.d/frr.list
# update and install FRR
RUN sudo apt update 
RUN sudo apt -y install frr frr-pythontools frr-rpki-rtrlib
RUN echo "zebrasrv      2600/tcp                 # zebra service" | sudo tee -a /etc/services