FROM ubuntu:22.04
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y ca-certificates curl gnupg lsb-release tcpdump iputils-ping sudo netbase
RUN curl -fsSL https://packages.nlnetlabs.nl/aptkey.asc | sudo gpg --dearmor -o /usr/share/keyrings/nlnetlabs-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/nlnetlabs-archive-keyring.gpg] https://packages.nlnetlabs.nl/linux/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/nlnetlabs.list > /dev/null
RUN sudo apt update
RUN sudo apt -y install nginx
RUN sudo apt install krill
RUN rm -f /etc/nginx/sites-enabled/default
COPY ./p1/repo.org /etc/nginx/sites-enabled
COPY ./p1/krill.conf /etc
COPY ./p1/nginx-selfsigned.key /etc/ssl/private/nginx-selfsigned.key
COPY ./p1/nginx-selfsigned.crt /etc/ssl/certs/nginx-selfsigned.crt
COPY ./p1/dhparam.pem /etc/nginx/dhparam.pem
#RUN service nginx start