FROM ubuntu:22.04
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y ca-certificates lsb-release net-tools curl tcpdump iputils-ping sudo gnupg2 vim netbase
# Add the GPG key from NLnet Labs:
RUN curl -fsSL https://packages.nlnetlabs.nl/aptkey.asc | sudo gpg --dearmor -o /usr/share/keyrings/nlnetlabs-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/nlnetlabs-archive-keyring.gpg] https://packages.nlnetlabs.nl/linux/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/nlnetlabs.list > /dev/null
# update and install routinator
RUN sudo apt update 
RUN sudo apt -y install routinator
RUN sudo useradd rpki
RUN echo "rpki:cache" | chpasswd
